import type { Metadata } from "next";
import "./globals.scss";
import { FormProvider } from "@/Contexts/FormProvider";
import { TtTravels } from "@/styles/fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={TtTravels.className}>
        <FormProvider>{children}</FormProvider>
      </body>
    </html>
  );
}
